"""add room type to rooms and bookings

Revision ID: 31f8ef823b7a
Revises: 6544a7048c6f
Create Date: 2026-08-25 18:49:12.031970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f8ef823b7a'
down_revision: Union[str, Sequence[str], None] = '6544a7048c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    room_type = sa.Enum("PRIVATE", "SHARED", name="roomtype")
    room_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "rooms",
        sa.Column("room_type", room_type, nullable=True)
    )

    op.execute("""
        UPDATE rooms
        SET room_type = 'PRIVATE'
    """)

    op.alter_column(
        "rooms",
        "room_type",
        nullable=False
    )

    op.add_column(
        "bookings",
        sa.Column("room_type", room_type, nullable=True)
    )

    op.execute("""
        UPDATE bookings b
        SET room_type = r.room_type
        FROM rooms r
        WHERE b.room_id = r.room_id
    """)

    op.alter_column(
        "bookings",
        "room_type",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_contains_several_groups', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'room_type')
    op.drop_column('bookings', 'room_type')
    # ### end Alembic commands ###
