"""update ExcludeConstrain

Revision ID: 36dbc3cffbc2
Revises: 31f8ef823b7a
Create Date: 2026-08-25 19:34:31.973814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dbc3cffbc2'
down_revision: Union[str, Sequence[str], None] = '31f8ef823b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_contains_several_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_contains_several_groups', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
