"""add new relations

Revision ID: 9fdbad7aaba4
Revises: ad6f738e58cf
Create Date: 2026-08-21 17:35:20.764486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdbad7aaba4'
down_revision: Union[str, Sequence[str], None] = 'ad6f738e58cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorites', 'rooms', ['room_id'], ['room_id'])
    op.add_column('rooms', sa.Column('is_contains_several_groups', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_contains_several_groups')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'room_id')
    # ### end Alembic commands ###
