"""Normalize property address

Revision ID: b7cbeb0a9613
Revises: 1bfcfd64d9b4
Create Date: 2026-08-23 17:12:22.254108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cbeb0a9613'
down_revision: Union[str, Sequence[str], None] = '1bfcfd64d9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('country', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('city', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('street', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('house_number', sa.String(), nullable=False))
    op.alter_column('properties', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('properties', 'address')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('properties', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('properties', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('properties', 'house_number')
    op.drop_column('properties', 'street')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'country')
    # ### end Alembic commands ###
