"""Add property_amenities

Revision ID: d78901deaf11
Revises: dd12cc3aa399
Create Date: 2026-08-22 19:27:52.349273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78901deaf11'
down_revision: Union[str, Sequence[str], None] = 'dd12cc3aa399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_amenities',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.amenity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'amenity_id')
    )
    op.alter_column('favorites', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('property_amenities')
    # ### end Alembic commands ###
