"""Add rating and reviews_count to properties

Revision ID: e7db7c500609
Revises: b7cbeb0a9613
Create Date: 2026-08-23 18:26:47.484785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7db7c500609'
down_revision: Union[str, Sequence[str], None] = 'b7cbeb0a9613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('properties', sa.Column('reviews_count', sa.Integer(), nullable=False))
    op.create_check_constraint('check_rating_range_properties', 'properties', 'rating >= 0 AND rating <= 10')
    op.create_check_constraint('check_rating_range_reviews', 'reviews', 'rating >= 1 AND rating <= 10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_rating_range_reviews', 'reviews', type_='check')
    op.drop_constraint('check_rating_range_properties', 'properties', type_='check')
    op.drop_column('properties', 'reviews_count')
    op.drop_column('properties', 'rating')
    # ### end Alembic commands ###
